apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.app }}
spec:
  ports:
  - port: 3306
    name: web
  clusterIP: None 
  selector:
    app: {{ .Values.mariadb.app }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: {{ .Values.mariadb.app }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mariadb.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.mariadb.app }}
    spec:
      imagePullSecrets:
      - name: ecr-registry-key
      containers:
      - name: {{ .Values.mariadb.app }}
        image: {{ .Values.mariadb.image }}
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-app-secret
              key: password
        - name: MARIADB_DATABASE
          value: yarin_db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.mariadb.storage }}

